apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  values:
    env:
      DOMAIN: "https://vaultwarden-dev.${tailnet_domain}"

    ingress:
      enabled: true
      className: "tailscale"
      annotations:
        tailscale.com/hostname: "vaultwarden-dev"
      hosts:
        - host: "vaultwarden-dev.${tailnet_domain}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "vaultwarden-dev.${tailnet_domain}"
