apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  values:
    ingressRoute:
      dashboard:
        enabled: false

    extraObjects:
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: traefik-dashboard
          namespace: traefik-system
          annotations:
            tailscale.com/hostname: "traefik-dev"
        spec:
          ingressClassName: "tailscale"
          rules:
            - host: "traefik-dev.${tailnet_domain}"
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: traefik
                        port:
                          number: 9000
          tls:
            - hosts:
                - "traefik-dev.${tailnet_domain}"
