apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:ImLZoPk5OLtejRlIV19w5zI=,iv:7MA2tEOp29Op/geykoSGRsOSUoKl/uKC1dJUDjPguwQ=,tag:oh+CVlVLmb/8W35mSN2GEQ==,type:str]
  client_secret: ENC[AES256_GCM,data:lEzn7ig1FIGCMr8d9jasZNh6qxjKDh0dz4TUlqMnSbpsooyS0w61vka6nf/Ng+atfbKccyQyIxF5u9F5QTOnAQ==,iv:/ilQnd/D+V1n++rCVw161zjf3CtLV1N5rwM7gAaJg/Y=,tag:eUJ6g4/8A5j3akU4El6UXQ==,type:str]
sops:
  age:
    - recipient: age1f8ulqpr26va0d7wcjymz3qmdx7zng652pyanxx4c2kk0yltgjayqv57ta7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSEs3Q3NiUEprTXhtVGZr
        dk9OSVJQb0ROL24xWmsxZHQvTW9RZGRpY1FRCkxnWXloaHRGZHRKdG4zSndsOExR
        eWZzTnoyZW9QSTArT3F2a0k5dkpaZWcKLS0tIHRxNlU0L2s2SG1jSW9BT2J2eTNt
        Z210bFhzQ2FnUVlVTDdHaE5aQllyOFEKBdkGdOnTpBVgyJxRmYDXEVa91LnNsWZB
        ORjt+IiY+2barKUVbM/3P3dfbpy+otyR7+yKid0rn73JEGH7ETB+pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T13:42:41Z"
  mac: ENC[AES256_GCM,data:od0MCOMoe9nxSnM6UqbUcBSd7jdJe2xzN5tO9p4CaQpOB8/NpwKUx9tijIhVtWOK/ZuEr5J+uqWSg4W3fvYEG3PgxkqACzR6hd3REWYlbuQFZEtOjfTtCise9LLZgDW7+0s8NgSgTFKKWDE6b5f/lqwQLLgepn0HF0TNblb5QZw=,iv:TiF+HeP5gfx1b6k3X81yN7QxQN3eMgQPlACBBfUNW4I=,tag:6VSAP3p4DQgA8byWftIRcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
