apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:4uhsStUhUsnBUJCkL2ij5fM=,iv:KUPXiTxb4WXUJtoK06xrx40B/Iy0I4YpqdEwjs8BdSk=,tag:2dfxwv4Em61cZSXdoNXkag==,type:str]
    client_secret: ENC[AES256_GCM,data:pb1rCVVLewEq7mQcnjv6lTI4xO4R+Xax48BKzDFuReLwzkN8eqJAAzd2yOJbJUDL66a/PSuvb/5KsWG6R8l45g==,iv:pU2Nx8z9e0vs68AOzEeNmuJw9l3d3/1tjqRxv8G/yBw=,tag:W7cU/+XzarMgff6l7zO7dA==,type:str]
sops:
    age:
        - recipient: age1f8ulqpr26va0d7wcjymz3qmdx7zng652pyanxx4c2kk0yltgjayqv57ta7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZFFib3dHWkNURDFtdFdw
            TndTOVY4K2hPN3FTcndkb0FkSnRncS9vWXlzClVRVGNJd3RQTHpuVGl2OElDM2FY
            YVI3UmJNRExtempwWmdIL1YxNG8ySDQKLS0tIEk5ci80T2R6MElvOVRYZnBQN214
            NVMrcEQxeWJkaENmRVVjZHppdFNvckUK/MSjeeXdj6/eh2Z3vF/E2GPtsbmm3/Z6
            UJe4cyC5hQdwFrH6U1skXnFRFim+QtoJgroIUYQk78jX+ydngVl9gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T14:07:08Z"
    mac: ENC[AES256_GCM,data:vGXRQOQWkJ1Ni5GeniyEo6AJ4JihTvzv7coly2G+ZN0JqEQNlgaXif0ftMXSoWJLks6nFD6glqxr/gmLrT0F1dvDAEQ+F5BccaHHCbmdimM2CMLyzi/REWueLvns9pdd5GHl3NX3nTwDFCM3LItr4Zbb77fpCTBKf1PAl5LGgz8=,iv:NEv9yYglMb9nNei4QMm6fm3B6sOSS++MqfnaAy6MYF4=,tag:7aY1/rNpbn+iu35j7diCVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
