apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  values:
    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/hostname: "gitops-dev"
      hosts:
        - host: "gitops-dev.${tailnet_domain}"
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: weave-gitops
                  port:
                    number: 9001
      tls:
        - hosts:
            - "gitops-dev.${tailnet_domain}"
