apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: weave-gitops
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:ndtwJjFDwhgf1wWCVsyO/ZVKTOiazt/wueT27t5bTUoa+1meXXr+u8eoA1i4XSN/7qOujkN8f3aN/SGR,iv:dSFRXGcchS5AQV6lCb54lc/Wy7FzM91avH7Mjx3XElE=,tag:wZlLEITe0rNkvcI0BSCDGw==,type:str]
sops:
  age:
    - recipient: age1f8ulqpr26va0d7wcjymz3qmdx7zng652pyanxx4c2kk0yltgjayqv57ta7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSjRjL05MaThnZGZFSy9j
        OUJUaHl0THhmSTJuZStHL09SV3NFTjFOaXhrCkU2ZUwxNUhhcU9UUzV2aGZlL0hi
        dzJVN1lYRXgxREhmYUFSS1plQjdaZTgKLS0tIDBlVTQ1d0g4WUYzMkQyZGlDRVIz
        b1VFRlkzb2xkZkpMVnUxeWtFNGJ0VFUKQ2sgDfQhYNEJbWBYO6dxGyZ2HEnO4FdO
        hzubz0uiUzpvC3X4sFEiuOxxR9wmDqK9FoRLktm+tL8Imuvir0Bgag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T20:31:13Z"
  mac: ENC[AES256_GCM,data:hayTTcjcKVE2eCR8mlwaMDYaSLkx+qo5Ojb8819h4fb3/OfotXI7cIPkj/Fj+O9kM6pyx0z9Ql+TqryyAR9ZV41b+x1jlGW12QjK7ehRb0OJU2NL4KJexo+CaZHGVAhxkNcjSDpQJvsrGQtBHFiZYy0kKcZaZTqhazjpCekMEN4=,iv:n5s/0Hpk16U2Mm9wyySZOsKvVe4df4GrQC0NLtIeWYE=,tag:YaMae356Gpms3DuRjkeOpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
